# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master



jobs:
- job: Build
  strategy:
    matrix:
      Windows:
        TARGET_POOL: 'webapp-harpia-pool'
        TARGET_OS: 'Windows_NT'
      Linux:
        TARGET_POOL: 'moving'
        TARGET_OS: 'Linux'
      Mac:
        TARGET_POOL: 'webapp-harpia-pool'
        TARGET_OS: 'Darwin'

  pool:
    name: $(TARGET_POOL)
    demands: agent.os -equals $(TARGET_OS)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install --registry=https://registry.npmjs.org --unsafe-perm
      npm install --global --registry=https://registry.npmjs.org @totvs/tds-dev-utils typescript
      npm run build-i18n:totvs -- --profile
      npm run build -- --targets=deb,rpm,tar.gz -LLLL --company=totvs
    displayName: 'npm install and build'
