trigger:
- master

stages:
- stage: TOTVS
  displayName: "TOTVS"

  jobs:
  - job: Build
    strategy:
      matrix:
        Windows:
          TARGET_POOL: 'webapp-harpia-pool'
          TARGET_OS: 'Windows_NT'
          TARGET_INSTALLER: 'nsis,zip'
        Linux:
          TARGET_POOL: 'moving'
          TARGET_OS: 'Linux'
          TARGET_INSTALLER: 'deb,rpm,tar.gz'
        Mac:
          TARGET_POOL: 'webapp-harpia-pool'
          TARGET_OS: 'Darwin'
          TARGET_INSTALLER: 'default'

    pool:
      name: $(TARGET_POOL)
      demands: agent.os -equals $(TARGET_OS)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install --registry=https://registry.npmjs.org --unsafe-perm
        npm install --global --registry=https://registry.npmjs.org @totvs/tds-dev-utils typescript
        npm run build-i18n:totvs -- --profile
        npm run build -- --targets=$(TARGET_INSTALLER) -LLLL --company=totvs
      displayName: 'npm install and build'
